added build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,56 +1,49 @@
-name: SonarCloud
+name: Build
+
 on:
   push:
     branches:
       - main
-  pull_request:
-    branches: [ "main" ]
-    types: [opened, synchronize, reopened]
-  workflow_dispatch:
-permissions:
-  pull-requests: read
 
 jobs:
   build:
-    name: Build and analyze
+    name: Build
     runs-on: ubuntu-latest
+    permissions: read-all
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v1
         with:
           java-version: 17
-          distribution: 'zulu' # Alternative distribution options are available.
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v3
+      - name: Cache SonarQube packages
+        uses: actions/cache@v1
         with:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
       - name: Cache Maven packages
-        uses: actions/cache@v3
+        uses: actions/cache@v1
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
       - name: Build and analyze
         env:
-          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # Needed to get PR information, if any
+          GITHUB_TOKEN: ${{ secrets.G_TOKEN}}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=chaitanya-087_cycleshop-rest-api
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cycle-shop-rest-api -Dsonar.projectName='cycle-shop-rest-api'
       - name: Check Code Coverage
         run: |
-            mvn jacoco:prepare-agent verify
-            mvn jacoco:report
-            coverage=$(grep -Po 'Total[^%]*\K[0-9.]+' target/site/jacoco/index.html)
-            if (( $(echo "$coverage >= 80" | bc -l) )); then
-              echo "Code coverage is above 80%"
-            else
-              echo "Code coverage is below 80%"
-              exit 1  # Fail the workflow if coverage is below 80%
-            fi
-      - name: Pull Request Stats
-        uses: flowwer-dev/pull-request-stats@v2.11.0
-    
+          mvn jacoco:prepare-agent verify
+          mvn jacoco:report
+          coverage=$(grep -Po 'Total[^%]*\K[0-9.]+' target/site/jacoco/index.html)
+          if (( $(echo "$coverage >= 80" | bc -l) )); then
+            echo "Code coverage is above 80%"
+          else
+            echo "Code coverage is below 80%"
+            exit 1  # Fail the workflow if coverage is below 80%
+          fi
