removed coverage check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,49 +1,54 @@
-name: Build
-
+name: SonarCloud
 on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
+    types: [opened, synchronize, reopened]
+  workflow_dispatch:
+permissions:
+  pull-requests: read
 
 jobs:
   build:
-    name: Build
+    name: Build and analyze
     runs-on: ubuntu-latest
-    permissions: read-all
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
       - name: Set up JDK 17
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v3
         with:
           java-version: 17
-      - name: Cache SonarQube packages
-        uses: actions/cache@v1
+          distribution: 'zulu' # Alternative distribution options are available.
+      - name: Cache SonarCloud packages
+        uses: actions/cache@v3
         with:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
       - name: Cache Maven packages
-        uses: actions/cache@v1
+        uses: actions/cache@v3
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
       - name: Build and analyze
         env:
-          GITHUB_TOKEN: ${{ secrets.G_TOKEN}}
+          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cycle-shop-rest-api -Dsonar.projectName='cycle-shop-rest-api'
-      - name: Check Code Coverage
-        run: |
-          mvn jacoco:prepare-agent verify
-          mvn jacoco:report
-          coverage=$(grep -Po 'Total[^%]*\K[0-9.]+' target/site/jacoco/index.html)
-          if (( $(echo "$coverage >= 80" | bc -l) )); then
-            echo "Code coverage is above 80%"
-          else
-            echo "Code coverage is below 80%"
-            exit 1  # Fail the workflow if coverage is below 80%
-          fi
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=chaitanya-087_cycleshop-rest-api
+      # - name: Check Code Coverage
+      #   run: |
+      #       mvn jacoco:prepare-agent verify
+      #       mvn jacoco:report
+      #       coverage=$(grep -Po 'Total[^%]*\K[0-9.]+' target/site/jacoco/index.html)
+      #       if (( $(echo "$coverage >= 80" | bc -l) )); then
+      #         echo "Code coverage is above 80%"
+      #       else
+      #         echo "Code coverage is below 80%"
+      #         exit 1  # Fail the workflow if coverage is below 80%
+      #       fi
